# Generated by Django 3.1 on 2020-08-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200804_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secret',
            name='expiry',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='uuid',
            field=models.CharField(default='uuidtest', max_length=120),
        ),
    ]
