# Generated by Django 3.1 on 2020-08-04 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200804_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='expiry',
            field=models.DateField(default=datetime.date(2020, 8, 5)),
        ),
    ]
