# Generated by Django 3.1 on 2020-08-05 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200804_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='expiry',
            field=models.DateTimeField(default=datetime.date(2020, 8, 6)),
        ),
    ]
