# Generated by Django 3.1 on 2020-08-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200805_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='access_code',
            field=models.CharField(default='default_access_code', max_length=120),
        ),
    ]
